name: EchoTrace
folia-supported: true
version: '${project.version}'
main: echotrace.Main
api-version: '1.21'
authors: [ Mitality ]
description: Easily find your friends
permissions:
  echotrace.update-notify:
    default: op
  echotrace.reload:
    default: op
  echotrace.trace:
    default: true
  echotrace.*:
    default: op
    children:
      echotrace.update-notify: true
      echotrace.reload: true
      echotrace.trace: true